// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdlJi1maAjL-7p86P0ihZnPDmS44ZFP-Q',
    appId: '1:990724550864:android:ac6886bc7fbf6f252c6ed5',
    messagingSenderId: '990724550864',
    projectId: 'mahibere-kidusan-tv-app',
    databaseURL: 'https://mahibere-kidusan-tv-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mahibere-kidusan-tv-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7reg008mAH0-AJ_7XfahpkVx6tNZ9LBk',
    appId: '1:990724550864:ios:ecefda8ca3e0e1042c6ed5',
    messagingSenderId: '990724550864',
    projectId: 'mahibere-kidusan-tv-app',
    databaseURL: 'https://mahibere-kidusan-tv-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mahibere-kidusan-tv-app.appspot.com',
    iosClientId: '990724550864-68qclbma3see9qfqpb68blql15o0d24v.apps.googleusercontent.com',
    iosBundleId: 'com.example.mkTvApp',
  );
}
